# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [13]:
import numpy as np

#### 2. Print your NumPy version.

In [14]:
np.__version__

'1.24.3'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [30]:
a = np.empty((2, 3, 5))

In [31]:
a = np.random.random((2, 3, 5))


In [32]:
a = np.random.rand(2, 3, 5)

In [33]:
a = np.random.random_sample((2, 3, 5))

#### 4. Print *a*.


In [41]:
a = np.random.random_sample((2, 3, 5))
a

array([[[0.87166264, 0.83911622, 0.79044729, 0.47329412, 0.67061245],
        [0.76233594, 0.46289658, 0.08054049, 0.19747995, 0.82508564],
        [0.01687333, 0.95110209, 0.15393184, 0.35905835, 0.93890966]],

       [[0.86524148, 0.3255602 , 0.73709317, 0.45112583, 0.78459549],
        [0.65553819, 0.54225705, 0.31440326, 0.40598145, 0.27781631],
        [0.03955705, 0.19293783, 0.57066319, 0.16896064, 0.32721126]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [23]:
dim = [5, 2, 3]  # 5 capas, 2 filas, 3 columnas

b = np.ones(dim)



#### 6. Print *b*.


In [22]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [34]:
a.size == b.size

True

In [35]:
a.size

30

In [36]:
b.size

30

#### 8. Are you able to add *a* and *b*? Why or why not?


In [42]:
np.add(a, b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [43]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [ ]:
No se puede porque no tienen las mismas dimensiones y de tamaño.
No coinciden en filas ni en columnas

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [44]:
#shape de un array NumPy devuelve una tupla que representa la forma del array, es decir, las dimensiones del array y el tamaño de cada dimensión
b.T.shape

(3, 2, 5)

In [45]:

b.transpose(0, 1, 2).shape

(5, 2, 3)

In [47]:
b.transpose(1,2,0).shape

(2, 3, 5)

In [48]:
a + b.transpose(1, 2, 0)

array([[[1.87166264, 1.83911622, 1.79044729, 1.47329412, 1.67061245],
        [1.76233594, 1.46289658, 1.08054049, 1.19747995, 1.82508564],
        [1.01687333, 1.95110209, 1.15393184, 1.35905835, 1.93890966]],

       [[1.86524148, 1.3255602 , 1.73709317, 1.45112583, 1.78459549],
        [1.65553819, 1.54225705, 1.31440326, 1.40598145, 1.27781631],
        [1.03955705, 1.19293783, 1.57066319, 1.16896064, 1.32721126]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [49]:
#la c es la matriz transpuesta
c = b.transpose(1, 2, 0)

In [50]:
# d es la suma de ambas

d = np.add(a, c)

d

array([[[1.87166264, 1.83911622, 1.79044729, 1.47329412, 1.67061245],
        [1.76233594, 1.46289658, 1.08054049, 1.19747995, 1.82508564],
        [1.01687333, 1.95110209, 1.15393184, 1.35905835, 1.93890966]],

       [[1.86524148, 1.3255602 , 1.73709317, 1.45112583, 1.78459549],
        [1.65553819, 1.54225705, 1.31440326, 1.40598145, 1.27781631],
        [1.03955705, 1.19293783, 1.57066319, 1.16896064, 1.32721126]]])

In [ ]:
#Funciona porque tienen el mismo tamaño y dimensión, después de hacer la transpuesta.

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [51]:
a

array([[[0.87166264, 0.83911622, 0.79044729, 0.47329412, 0.67061245],
        [0.76233594, 0.46289658, 0.08054049, 0.19747995, 0.82508564],
        [0.01687333, 0.95110209, 0.15393184, 0.35905835, 0.93890966]],

       [[0.86524148, 0.3255602 , 0.73709317, 0.45112583, 0.78459549],
        [0.65553819, 0.54225705, 0.31440326, 0.40598145, 0.27781631],
        [0.03955705, 0.19293783, 0.57066319, 0.16896064, 0.32721126]]])

In [52]:
d

array([[[1.87166264, 1.83911622, 1.79044729, 1.47329412, 1.67061245],
        [1.76233594, 1.46289658, 1.08054049, 1.19747995, 1.82508564],
        [1.01687333, 1.95110209, 1.15393184, 1.35905835, 1.93890966]],

       [[1.86524148, 1.3255602 , 1.73709317, 1.45112583, 1.78459549],
        [1.65553819, 1.54225705, 1.31440326, 1.40598145, 1.27781631],
        [1.03955705, 1.19293783, 1.57066319, 1.16896064, 1.32721126]]])

In [ ]:
#La diferencia es que la matriz d ha incrementado en 1, devido a la suma de la matriz a con la b, convirtiendose finalmente en d

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [53]:
np.multiply(a, c)

array([[[0.87166264, 0.83911622, 0.79044729, 0.47329412, 0.67061245],
        [0.76233594, 0.46289658, 0.08054049, 0.19747995, 0.82508564],
        [0.01687333, 0.95110209, 0.15393184, 0.35905835, 0.93890966]],

       [[0.86524148, 0.3255602 , 0.73709317, 0.45112583, 0.78459549],
        [0.65553819, 0.54225705, 0.31440326, 0.40598145, 0.27781631],
        [0.03955705, 0.19293783, 0.57066319, 0.16896064, 0.32721126]]])

In [54]:
#o también

a * c

array([[[0.87166264, 0.83911622, 0.79044729, 0.47329412, 0.67061245],
        [0.76233594, 0.46289658, 0.08054049, 0.19747995, 0.82508564],
        [0.01687333, 0.95110209, 0.15393184, 0.35905835, 0.93890966]],

       [[0.86524148, 0.3255602 , 0.73709317, 0.45112583, 0.78459549],
        [0.65553819, 0.54225705, 0.31440326, 0.40598145, 0.27781631],
        [0.03955705, 0.19293783, 0.57066319, 0.16896064, 0.32721126]]])

In [58]:
e = a * c

e

array([[[0.87166264, 0.83911622, 0.79044729, 0.47329412, 0.67061245],
        [0.76233594, 0.46289658, 0.08054049, 0.19747995, 0.82508564],
        [0.01687333, 0.95110209, 0.15393184, 0.35905835, 0.93890966]],

       [[0.86524148, 0.3255602 , 0.73709317, 0.45112583, 0.78459549],
        [0.65553819, 0.54225705, 0.31440326, 0.40598145, 0.27781631],
        [0.03955705, 0.19293783, 0.57066319, 0.16896064, 0.32721126]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [59]:
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [60]:
a is e

False

In [61]:
id(a)


2575492494992

In [62]:
id(e)

2575507428560

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [55]:
d_max = d.max()

d_max

1.9511020879973544

In [56]:
d_mean = d.mean()

d_mean

1.5017429653567342

In [57]:
d_min = d.min()

d_min

1.0168733264375318

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [63]:
f = np.empty((2, 3, 5))  

f

array([[[0.87166264, 0.83911622, 0.79044729, 0.47329412, 0.67061245],
        [0.76233594, 0.46289658, 0.08054049, 0.19747995, 0.82508564],
        [0.01687333, 0.95110209, 0.15393184, 0.35905835, 0.93890966]],

       [[0.86524148, 0.3255602 , 0.73709317, 0.45112583, 0.78459549],
        [0.65553819, 0.54225705, 0.31440326, 0.40598145, 0.27781631],
        [0.03955705, 0.19293783, 0.57066319, 0.16896064, 0.32721126]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [64]:
for capa in range(f.shape[0]):   # 2 capas
    
    for fila in range(f.shape[1]):   # 3 filas
        
        for col in range(f.shape[2]):  # 5 columnas
            
            
            if d_min == d[capa][fila][col]: # si es el minimo ponme cero en f
                
                f[capa][fila][col] = 0
                
            
            elif d_min < d[capa][fila][col] < d_mean: # si esta entre el minimo y la media ponme 25
                
                f[capa][fila][col] = 25
                
                
            elif d_mean == d[capa][fila][col]: # si es la media ponme 50 en f
                
                f[capa][fila][col] = 50
                
                
            elif d_mean < d[capa][fila][col] < d_max: # si esta entre la media y el maximo ponme 75
                
                f[capa][fila][col] = 75
                
                
            elif d_max == d[capa][fila][col]: # si es el maximo ponme 100 en f
                
                f[capa][fila][col] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [65]:
f

array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  25.,  25.,  25.,  75.],
        [  0., 100.,  25.,  25.,  75.]],

       [[ 75.,  25.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 25.,  25.,  75.,  25.,  25.]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [66]:
f =  f.astype('str')   # a formato string


for capa in range(f.shape[0]):   # 2 capas
    
    for fila in range(f.shape[1]):   # 3 filas
        
        for col in range(f.shape[2]):  # 5 columnas
            
            
            if d_min == d[capa][fila][col]: # si es el minimo ponme A en f
                
                f[capa][fila][col] = 'A'
                
            
            elif d_min < d[capa][fila][col] < d_mean: # si esta entre el minimo y la media ponme B
                
                f[capa][fila][col] = 'B'
                
                
            elif d_mean == d[capa][fila][col]: # si es la media ponme C en f
                
                f[capa][fila][col] = 'C'
                
                
            elif d_mean < d[capa][fila][col] < d_max: # si esta entre la media y el maximo ponme D
                
                f[capa][fila][col] = 'D'
                
                
            elif d_max == d[capa][fila][col]: # si es el maximo ponme E en f
                
                f[capa][fila][col] = 'E'
        

In [67]:
f

array([[['D', 'D', 'D', 'B', 'D'],
        ['D', 'B', 'B', 'B', 'D'],
        ['A', 'E', 'B', 'B', 'D']],

       [['D', 'B', 'D', 'B', 'D'],
        ['D', 'D', 'B', 'B', 'B'],
        ['B', 'B', 'D', 'B', 'B']]], dtype='<U32')